In [1]:
import numpy as np

In [4]:
lst=[1,2,3]
np.array(lst) #make array from list

array([1, 2, 3])

In [5]:
my_mat=[[1,2,3],[4,5,6]]
np.array(my_mat)#multi dimensional array from list of list

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0,11,2)#same as range function but returns array

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros((3,4))#returns a zero array of given dim

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2,3))#returns a one array of given dim

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(4)#returns an identity array of given dim

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.linspace(0,5,11)#returns a 1D array of equispaced points

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
np.random.rand(5,2)#returns number between 0 and 1 which are equally probable

array([[0.33288929, 0.18927684],
       [0.46731173, 0.4329226 ],
       [0.96971802, 0.15102625],
       [0.15333597, 0.58365489],
       [0.27797493, 0.57409273]])

In [14]:
np.random.randn(10)#returns number from gausian or normal distribution

array([ 1.20560251, -0.80045805,  0.61696019,  0.11102481,  1.27034587,
       -0.13109972, -1.05546871,  0.68810536,  0.16561684,  2.20426466])

In [15]:
np.random.randint(5,11,10)#returns random integers

array([ 5,  7,  9, 10,  7,  6,  9,  8,  9,  5])

In [18]:
arr=np.arange(25)
arr.reshape(5,5)#you can change shape of array total no. of elements should be equal

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()#returns max element
ranarr.min()#returns min element
ranarr.argmax()#returns index of max 
ranarr.argmin()#returns index of min
ranarr.std()#returns standard div
ranarr.shape # returns sahp