In [1]:
import numpy as np

In [3]:
arr=np.arange(9)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr[0][2]#return the element in row 0 colum 2
arr[0,2]#return the element in row 0 colum 2

2

In [7]:
arr[1:,:2]#index slicing to get sub matrix

array([[3, 4],
       [6, 7]])

In [8]:
arr=np.arange(10,25)
bool_arr=arr>17#makes a boolean array checking that conditon
arr[bool_arr]

array([18, 19, 20, 21, 22, 23, 24])

# Array operations


In [12]:
arr=np.arange(11)
arr
arr+arr
arr-arr
arr+50
arr*2
arr/4
arr*arr
arr/arr#gives warning when zero is divided
arr**3

C:\Users\adipu\AppData\Local\Temp\ipykernel_19548\2801925547.py:9: RuntimeWarning: invalid value encountered in divide
  arr/arr#gives warning when zero is divided


array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

# some universal functions

In [11]:
arr=np.arange(1,6)
np.sqrt(arr)
np.exp(arr)
np.max(arr)
np.sin(arr)
np.cos(arr)
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])