<a href="https://colab.research.google.com/github/githuanand/IIT-BHUBNESHWAR-DAY-01/blob/main/python_basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***IIT BHUBANESHWAR WORKSHOP ON AI-ML WITH DATA SCIENCE***

In [ ]:
print("Hello World!!")

Hello World!!


In [ ]:
x=int(input())

3


# **LISTS**

In [ ]:
arr=[1,2,3,43,50,67] #initialising a list
print(arr[0])#indexing a list(zero based indexing)
print(arr[2:]) #slicing a list
print(arr[2:5:2]) #slicing a list(start index,end index,step size)
print(len(arr))#length of the index
print(arr.pop())#pops the last element
arr.append(101) #appends the element to the last of the list
print(arr)
arr.sort() #sorts in place
sorted(arr) #return a copy of the sorted arr

1
[3, 43, 50, 67]
[3, 50]
6
67
[1, 2, 3, 43, 50, 101]


[1, 2, 3, 43, 50, 101]

In [ ]:
#FOR LOOPS
for i in range(3,9,3):
  print(i)
for i in arr:
  print(i,end=" ")

3
6


In [ ]:
for i in arr:
  print(i,end=" ")

1 2 3 43 50 101 

In [ ]:
#while loops

i=0
while i<5:
  print(i)
  i+=1
  #condition:

0
1
2
3
4


In [ ]:
while arr:
  print(arr.pop())

101
50
43
3
2
1


In [ ]:
#TUPLES
tuple=(1,2,3)
arr=[1,2,3]
s='hello world'


# ***Strings***

In [ ]:
s='hello t world'

In [ ]:
print(s[1])
print(s[4:])
print(s[4:10])
s.split('l')
s.split()

e
o t world
o t wo


['hello', 't', 'world']

In [ ]:
dict={'a':1,'b':2,'c':3}

In [ ]:
dict['a']='2'
dict['a']

'2'

# ***FUNCTIONS***

In [ ]:
def hello():
  print('hello world')

In [ ]:
hello()

hello world


# ***NUMPY-MODULE 1***

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(9)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[0][2]#return the element in row 0 colum 2
arr[0,2]#return the element in row 0 colum 2

2

In [ ]:
arr[1:,:2]#index slicing to get sub matrix

array([[3, 4],
       [6, 7]])

In [ ]:
arr=np.arange(10,25)
bool_arr=arr>17#makes a boolean array checking that conditon
arr[bool_arr]

array([18, 19, 20, 21, 22, 23, 24])

# **Array operations**


In [ ]:
arr=np.arange(11)
arr
arr+arr
arr-arr
arr+50
arr*2
arr/4
arr*arr
arr/arr#gives warning when zero is divided
arr**3

<ipython-input-41-b023bf7f9c7c>:9: RuntimeWarning: invalid value encountered in divide
  arr/arr#gives warning when zero is divided


array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
#some universal functions
arr=np.arange(1,6)
np.sqrt(arr)
np.exp(arr)
np.max(arr)
np.sin(arr)
np.cos(arr)
np.log(arr)
np.tan(arr)


array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])